version: '3'
services:
  rabbitMq:
    image: rabbitmq
    container_name: rabbitMq_container
  paymentserver:
    image: paymentserver
    container_name: paymentserver
    ports:
      - "8080:8080"
    build:
      context: ./paymentService
      dockerfile: ./Dockerfile
  tokenserver:
    image: tokenserver
    container_name: tokenserver
    ports:
      - "8181:8181"
    build:
      context: ./tokenService
      dockerfile: ./Dockerfile
  accountserver:
    image: accountserver
    container_name: accountserver
    ports:
      - "8383:8383"
    build:
      context: ./accountService
      dockerfile: ./Dockerfile